global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'gracewrap-demo'
    static_configs:
      - targets: ['host.docker.internal:8080']
    scrape_interval: 2s
    metrics_path: /metrics
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
